trigger:
- master
variables:
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/ecommerce-template'


stages:
- stage: build
  jobs:
  - job: build
    variables:
      group: ecrystal-dev
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: $(workingDirectory)
        command: install

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        workingDir: $(workingDirectory)
        command: custom
        customCommand: run-script build
      env:
        REACT_APP_SERVER_URL_PROD: $(API_URL)
        REACT_APP_SERVER_API_KEY: $(API_KEY)
    
    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(workingDirectory)/build'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: BuildOutputs

- stage: deploy
  jobs:
  - deployment: deploy
    pool:
      vmImage: vs2017-win2016
    variables:
      storageaccountname: ecrystalwebsite
    environment: 'Deploy to Storage'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: BuildOutputs

          - task: AzureFileCopy@3
            inputs:
              sourcePath: $(Pipeline.Workspace)/BuildOutputs
              azureSubscription: 'ecrystal-ui-pipeline'
              destination: azureBlob
              storage: $(storageaccountname)
              containerName: "$web" 